### ISSUE TITLE
How to get list of co-authors?

### ISSUE THREAD

**Issue by nemuo** [OrganicIrradiation/scholarly#12]
Thank you for the nice module.

I would like to get a list of co-authors of an author as follows.

```
author = next(scholarly.search_author('Steven A. Cholewiak')).fill();
for ca in author.coauthors:
  print ca;
```

However, the profile object does not have the list but only the one of publications.
How can I get the list of co-authors?

**Comment by OrganicIrradiation** [comment]
Retrieving co-authors is not currently implemented; however, I encourage you to add it and submit a pull request!

**Comment by OrganicIrradiation** [comment]
This has been added in PR https://github.com/OrganicIrradiation/scholarly/pull/15.
