### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by yhalk** [OrganicIrradiation/scholarly#16]
Hi,

I am constantly getting the following error:

requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

All requisite packages are installed - is it Google's policy on Scholar?

Thank you in advance!

**Comment by OrganicIrradiation** [comment]
Could you please confirm if this is still occurring? I haven't been able to replicate.

**Comment by OrganicIrradiation** [comment]
No response, so closing issue. Feel free to reopen if you're still experiencing the issue.
