### ISSUE TITLE
search_pubs_query() did not work ( Was I banned by the google scholar?)

### ISSUE THREAD

**Issue by FrankScarlet** [OrganicIrradiation/scholarly#17]
## Background
It is tricky to use this scholarly in China(mainland). So I use a VPS in US (ubuntu18.04 py3.6) to make it work.
I try to put the name of my teacher of the institute in the query, and collect the result to make it into a .json file.
Everything was fine when I succeed to read my first json. So I make a iteration to put all the teachers of the institute in the query and collect the result. But I find the following result is 0.(it likes [])
I wondered why and test it through terminal. I find that it will return like
```
Traceback() : File "<stdin>", line 1, in <module>
StopIteration
```
## Doubt
The other functions work properly. I try the example after this situation. I doubted that I test the 'search_pubs_query()' too many times to find how to extract the data with the generator. Google banned the ip of my vps because I required too many results.
 ( I set a limit in my code that it will just get 100 results at most. The number of the teachers in my institute is 75. I find a empty result at the second teacher)
I will test the function again tomorrow, maybe Google set a limit for one day?

**Comment by FrankScarlet** [comment]
I wait for a whole day and reconnect my vps to test whether the search_pubs_query() work properly.
It works again. I think it has a limit of search query a day. I will keep on writing my program to find if there are any other things we need to care for.

**Comment by sunchang0124** [comment]
the same problem here. It stops working suddenly. I don't know why. Did you found the reason? is there a limitation from Google Scholar?

**Comment by OrganicIrradiation** [comment]
The most likely reason for abruptly stopping is rate limiting by Google. The current code does not handle the CAPTCHA.

**Comment by Dennis1989** [comment]
I think the current problem is that after some crawling the captcha is actually not provided:

ERROR for site owner:
Invalid domain for site key

I mean it would be still beneficial if the program simply pauses and one can solve the captcha in a browser and then the crawler continues right? Any idea to realize this?

**Comment by felippemed** [comment]
Same for me... 

it is strange because it works for author

```
import scholarly


print(next(scholarly.search_author('Steven A. Cholewiak')))
{'_filled': False,
 'affiliation': 'Assistant Project Scientist, University of California, '
                'Berkeley',
 'id': '4bahYMkAAAAJ',
 'interests': [],
 'name': 'Steven A. Cholewiak',
 'url_picture': '/citations?view_op=small_photo&user=4bahYMkAAAAJ&citpid=3'}

```

but it doesn't work for query


```
print(next(search_pubs_query('Perception of physical stability and center of mass of 3D objects')))
Traceback (most recent call last):

  File "<ipython-input-15-087401951f8a>", line 1, in <module>
    print(next(search_pubs_query('Perception of physical stability and center of mass of 3D objects')))

StopIteration

```

**Comment by lqcata** [comment]
I think it is the problem of the reCAPTCHA. I did the search manually and was asked to click the figures of CAPTCHA, and I got the 403 error when I tried to open the bib link:

Your client does not have permission to get URL /scholar.bib?q=info:JsZd-SGNe6gJ:scholar.google.com/&output=citation&scisig=AAGBfm0AAAAAXMBbcmldq04Sj9M-iNS8JV_aA5a4K_Vw&scisf=4&ct=citation&cd=-1&hl=zh-CN from this server.
Please see Google's Terms of Service posted at http://www.google.com/terms_of_service.html

**Comment by seyyedmohammad** [comment]
search_pubs_query() has two challenges, first, StopIteration runtime Error on multiple publications query which uses for loop (on multiple queries) before search_pubs_query() can solve it. 
The next challenge on reCAPTCHA which uses free ssl proxies or fake-user agent on your python code and change your user-agent and IP every 10 requests, can solve it too.

**Comment by kirk86** [comment]
I just had the same issue today pretty the code usage looks like:
```
search_query = scholarly.search_pubs_query(txt)
results = list(search_query)
        for res in results:  
              score = _scholar_score(txt, res.bib)
            if score > maxscore: 
                maxscore = score
                 result = res
```
The errors that I see are have the following message:
```
Exception: Error: 429 Too Many Requests
```

**Comment by seyyedmohammad** [comment]
> I just had the same issue today pretty the code usage looks like:
> 
> ```
> search_query = scholarly.search_pubs_query(txt)
> results = list(search_query)
>         for res in results:  
>               score = _scholar_score(txt, res.bib)
>             if score > maxscore: 
>                 maxscore = score
>                  result = res
> ```
> 
> The errors that I see are have the following message:
> 
> ```
> Exception: Error: 429 Too Many Requests
> ```
> 
> My question is since this is a fork of some other repo, does this also handle cookies the same way as the original repo did?
> 
> I even tried to manually add a cookie from the scholar.google.com, but it didn't work regardless of FF or chrome. It seems that from comments on the old repo some folks where able to bypass the captcha and limit by explicitly setting the cookie value and the agent.
> 
> ```
> Traceback (most recent call last):
>   File "/Users/jm/miniconda3/envs/papers/bin/papers", line 5, in <module>
>     papers.bib.main()
>   File "/Users/jm/miniconda3/envs/papers/lib/python3.7/site-packages/papers/bib.py", line 1748, in main
>     extractcmd(o)
>   File "/Users/jm/miniconda3/envs/papers/lib/python3.7/site-packages/papers/bib.py", line 1671, in extractcmd
>     max_query_words=o.word_count,
>   File "/Users/jm/miniconda3/envs/papers/lib/python3.7/site-packages/papers/extract.py", line 187, in extract_pdf_metadata
>     return extract_txt_metadata(txt, search_doi, search_fulltext, **kw)
>   File "/Users/jm/miniconda3/envs/papers/lib/python3.7/site-packages/papers/extract.py", line 167, in extract_txt_metadata
>     bibtex = fetch_bibtex_by_fulltext_scholar(query_txt)
>   File "/Users/jm/miniconda3/envs/papers/lib/python3.7/site-packages/papers/config.py", line 220, in decorated
>     res = cache[key] = fun(doi)
>   File "/Users/jm/miniconda3/envs/papers/lib/python3.7/site-packages/papers/extract.py", line 238, in fetch_bibtex_by_fulltext_scholar
>     search_query = scholarly.search_pubs_query(txt)
>   File "/Users/jm/miniconda3/envs/papers/lib/python3.7/site-packages/scholarly/scholarly.py", line 289, in search_pubs_query
>     soup = _get_soup(_HOST+url)
>   File "/Users/jm/miniconda3/envs/papers/lib/python3.7/site-packages/scholarly/scholarly.py", line 90, in _get_soup
>     html = _get_page(pagerequest)
>   File "/Users/jm/miniconda3/envs/papers/lib/python3.7/site-packages/scholarly/scholarly.py", line 85, in _get_page
>     raise Exception('Error: {0} {1}'.format(resp.status_code, resp.reason))
> Exception: Error: 429 Too Many Requests
> ```

Use fake-user-agen python library or use sslproxies for IP rotation.

**Comment by SundeepPidugu** [comment]
@seyyedmohammad sample code of the implementation please.

**Comment by YupingBai** [comment]
> search_pubs_query() has two challenges, first, StopIteration runtime Error on multiple publications query which uses for loop (on multiple queries) before search_pubs_query() can solve it.
> The next challenge on reCAPTCHA which uses free ssl proxies or fake-user agent on your python code and change your user-agent and IP every 10 requests, can solve it too.

I have the same issue, how can I change IP and agent in the python code?

Thank you very much

**Comment by seyyedmohammad** [comment]
> @seyyedmohammad sample code of the implementation please.

You can use multiple websites that provide a proxy or IP rotator like www.proxyrotator.com or a free version like a sslproxies.org. The usage of them is very simple, just add a proxy to requests.get() function like this:

`request.get(url, proxies={<proxy_ip>})`

After that you can change you user-agent too, you should add headers like :

`headers = {
      User-Agent: <user_agent_string>
}
`
and then use in requests.get() function:

`requests.get(url, proxies={<proxy_ip>}, headers=headers)`

proxy rotator sites like www.proxyrotator.com give you User-Agent with proxy ip too. Then, you must have a global counter to change a proxy after a certain number of requests (like 20 requests).

**Comment by seyyedmohammad** [comment]
> > search_pubs_query() has two challenges, first, StopIteration runtime Error on multiple publications query which uses for loop (on multiple queries) before search_pubs_query() can solve it.
> > The next challenge on reCAPTCHA which uses free ssl proxies or fake-user agent on your python code and change your user-agent and IP every 10 requests, can solve it too.
> 
> I have the same issue, how can I change IP and agent in the python code?
> 
> Thank you very much

You can use multiple websites that provide a proxy or IP rotator like www.proxyrotator.com or a free version like a sslproxies.org. The usage of them is very simple, just add a proxy to requests.get() function like this:

request.get(url, proxies={<proxy_ip>})

After that you can change you user-agent too, you should add headers like :

headers = { User-Agent: <user_agent_string> } 
and then use in requests.get() function:

requests.get(url, proxies={<proxy_ip>}, headers=headers)

proxy rotator sites like www.proxyrotator.com give you User-Agent with proxy ip too. Then, you must have a global counter to change a proxy after a certain number of requests (like 20 requests).

**Comment by ipeirotis** [comment]
The version on git now supports proxies. I will close this for now.
