### ISSUE TITLE
Scholarly.py stopped working in .get_citedby() function

### ISSUE THREAD

**Issue by aksthapit** [OrganicIrradiation/scholarly#19]
Hi, 
("'NoneType' object has no attribute 'find'",) generated when trying to get cited_by information. 
`function _search_scholar_soup(soup) ,`  
`line : yield Publication(row, 'scholarly')`
I think google scholar format changed or something, I have tried tracking issue upto the line
`databox = __data.find('div', class_='gs_ri')` in Publication class. However, I am not that familiar with beautiful soup, please help.
Many thanks

**Comment by aksthapit** [comment]
I have now fixed the issue, closing now

**Comment by OrganicIrradiation** [comment]
I believe this is fixed in the latest version of the code, but would appreciate if you could confirm. Thanks!

**Comment by Jacobzhangjw** [comment]
Hi! OrganicIrradiation, Thanks for your great work! Everything works fine except get_citedby()

No exceptions were raised, but .get_citedby() function **return a empty list**. I've tried it either using you example or call by other publication object, they both return empty list.

**Comment by arafeh94** [comment]
I also have this issue

**Comment by nettrino** [comment]
I've had a similar issue where the fuction worked, however after a 403, kept returning an empty list.
