### ISSUE TITLE
Showing wrong publication year 

### ISSUE THREAD

**Issue by prvonline** [OrganicIrradiation/scholarly#23]
I tried using scholarly, it is greatly helping to extract the publications information from google scholar. However, I am facing a problem while showing year of publication. It is showing 1970 as the year of publication to many papers. Consider the publication title "Trust and reputation aware geographic routing method for wireless ad hoc networks", it was published in 2018, but the scholarly showing it as 1970.  Kindly resolve this issue. I have used the following code to get the publication year

author = scholarly.Author('scholar_id').fill()
for pub in author.publications:
     pub_data = pub.fill()
     if 'year' in pub_data:
         print(pub_data.bib['title'])
         print(pub_data.bib['year'])

**Comment by OrganicIrradiation** [comment]
I am unable to replicate this. Make sure to update to the latest version of scholarly and try:

```python
pub = scholarly.search_pubs_query('Trust and reputation aware geographic routing method for wireless ad hoc networks')
p = next(pub).fill()
print(p)

{'_filled': True,
 'bib': {'ENTRYTYPE': 'article',
         'ID': 'vamsi2018trust',
         'abstract': 'We consider the problem of secure geographic routing '
                     '(GR) in mobile wireless ad-hoc networks (WANETs). This '
                     'paper presents a dependable and pragmatic trust and '
                     'reputation aware geographic routing (TARA-GR) method for '
                     'mobile WANETs to achieve self-adaptability, scalability, '
                     'lightweight communication, and efficiency. It supports '
                     'the GR decisions by the dynamic computation of '
                     'consolidated trust value (CTV) of each node in the '
                     'network by integrating direct and indirect trust values. '
                     'With the calculated trust value, each …',
         'author': 'Vamsi, P Raghu and Kant, Krishna',
         'journal': 'International Journal of Ad Hoc and Ubiquitous Computing',
         'number': '2',
         'pages': '121--137',
         'publisher': 'Inderscience Publishers (IEL)',
         'title': 'Trust and reputation aware geographic routing method for '
                  'wireless ad hoc networks',
         'url': 'https://www.inderscienceonline.com/doi/abs/10.1504/IJAHUC.2018.089581',
         'volume': '27',
         'year': '2018'},
 'source': 'scholar',
 'url_scholarbib': 'https://scholar.googleusercontent.com/scholar.bib?q=info:84bTt6Wr5sgJ:scholar.google.com/&output=citation&scisig=AAGBfm0AAAAAXGSgtf4f6VqC0YBJOQ0prgma7-HxWZss&scisf=4&ct=citation&cd=0&hl=en'}
```

Closing but will reopen if you can provide an explicit example where there is an issue.

**Comment by dotman14** [comment]
Experiencing the same issue as @prvonline reported. Some publications are returning 1970 for year.

**Comment by JheeKeyth** [comment]
> Experiencing the same issue as @prvonline reported. Some publications are returning 1970 for year.
> 
> ```python
> pub = scholarly.search_author("Adam V. Maltese")
> p = next(pub).fill() 
> print(p.publications[7].fill().bib)
> 
> {'title': 'Breaking from Tradition: Unfulfilled Promises of Block Scheduling in Science.', 
> 'year': 1970, 
> 'url': 'https://eric.ed.gov/?id=EJ773255', 
> 'author': 'Adam V Maltese and Kirsten M Dexter and Robert H Tai and Philip M Sadler', 
> 'journal': 'Science Educator', 
> 'volume': '16', 
> 'number': '1',
> 'pages': '1-7', 
> 'publisher': 'National Science Education Leadership Association. PO Box 99381, Raleigh, NC 27624-9381', 
> 'abstract': <div class="gsc_vcd_value" id="gsc_vcd_descr"><div class="gsh_small"><div 
>            class="gsh_csp">With 66.7% of high school graduates from the class of 2004 enrolled in 
>            colleges or universities (United States Department of Labor, July 2005), the importance of 
>            high [......], 
> 'eprint': 'https://files.eric.ed.gov/fulltext/EJ773255.pdf'}
> ```

The same here. I have several articles returning 1970 in the year key.
