### ISSUE TITLE
Any suggestion for error 404?

### ISSUE THREAD

**Issue by Jacobzhangjw** [OrganicIrradiation/scholarly#24]
Hi! Thanks for your great work!

It seems that Goo block me after collecting 100 papers (2 keywords * 50 papers).
Any advises for handling this? Should I add more request headers? Thanks!

**Comment by ipeirotis** [comment]
This request https://github.com/OrganicIrradiation/scholarly/pull/26 allows the use of proxy for the request.

**Comment by Jacobzhangjw** [comment]
> This request #26 allows the use of proxy for the request.

Hi! Thanks for your advise! 

Besides proxy, I recommend if we could add a list of headers rather than a fixed one. Scholarly will be more useful if this project become robust for intensive collection work!

**Comment by OrganicIrradiation** [comment]
The issue is that the ReCAPTCHA flagging system is a black box, so it's unclear what triggers it. I've tried to have the code as accommodating as possible (including the long query delay in _get_page()), but it still triggers the ReCAPTCHA verification. So, it's an ongoing issue for this project.

**Comment by Tahlor** [comment]
Maybe if it detects "Please show you're not a robot" we could have it throw an error? I got hit with this on my first request ever and just assumed I was using it wrong.

**Comment by Tahlor** [comment]
I was hit with "Please show you're not a robot" with my first request ever. Since no error was thrown, I just assumed I was using it wrong. Do we need a PR to at least throw an error when the "Please show you're not a robot" page is returned?

**Comment by silvavn** [comment]
Addressed with proxy.
