### ISSUE TITLE
How to get year wise citations of a publication?

### ISSUE THREAD

**Issue by prvonline** [OrganicIrradiation/scholarly#25]
I have paper "Systematic Design of Trust Management Systems for Wireless Sensor Networks: A Review" which was published in 2014. Now, I want to see the year wise citation of this publication (i.e., number of citations in 2014, 2015,2016, 2017, 2018, and 2019). Is it possible with this package?

**Comment by ipeirotis** [comment]
I assume this pull request fixes the issue: https://github.com/OrganicIrradiation/scholarly/pull/26

**Comment by OrganicIrradiation** [comment]
As @ipeirotis mentioned, this was added in PR #26:

```python
>>> import pprint
>>> import scholarly
>>> search_query = scholarly.search_author('Le Cong 丛乐')
>>> author = next(search_query).fill()
>>> pub = author.publications[0].fill()
>>> pprint.pprint(pub.cites_per_year)
{2013: 279,
 2014: 841,
 2015: 1140,
 2016: 1591,
 2017: 1740,
 2018: 1729,
 2019: 763}
```
