### ISSUE TITLE
Connection over a proxy server

### ISSUE THREAD

**Issue by yhdelgado** [OrganicIrradiation/scholarly#31]
Dear all,

The module doesn't support connection over a proxy server. It would be very useful if the module includes support for proxy-based internet connection.

**Comment by ipeirotis** [comment]
Fixed in https://github.com/OrganicIrradiation/scholarly/pull/26 but the owner does not seem to merge the PR

**Comment by OrganicIrradiation** [comment]
I've merged PR #26, which adds this feature, as mentioned by @ipeirotis.
