### ISSUE TITLE
Cannot get all the author of one publication

### ISSUE THREAD

**Issue by yueyericardo** [OrganicIrradiation/scholarly#34]
for example:  
![img](https://yyrcd-1256568788.cos.na-siliconvalley.myqcloud.com/yyrcd/2019-04-05-191636.png)

**Comment by OrganicIrradiation** [comment]
The issue is that the Google Scholar page does not provide all of the authors on the initial search page. See: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=Less+is+more%3A+Sampling+chemical+space&btnG=

You would need to do ```next(search_query).fill()``` to get the full bibliography and author list.

**Comment by yueyericardo** [comment]
> The issue is that the Google Scholar page does not provide all of the authors on the initial search page. See: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=Less+is+more%3A+Sampling+chemical+space&btnG=
> 
> You would need to do `next(search_query).fill()` to get the full bibliography and author list.

I see, thanks for your reply!

**Comment by OrganicIrradiation** [comment]
No problem, please excuse the delayed response!
