### ISSUE TITLE
Tests failing due to search queries changing over time

### ISSUE THREAD

**Issue by cjekel** [OrganicIrradiation/scholarly#35]
These tests look for equality in the length of a google scholar query, and currently fail because the length of the query is now different.
- test_empty_keyword
- test_multiple_publications
- test_multiple_authors

Perhaps these tests should be framed as greater than, rather than strictly equal. For example:
```python
 self.assertEqual(len(authors), 54)
```
could be
```python
 self.assertTrue(len(authors) >= 10)
```

But maybe someone else has a better idea on how to do this.

**Comment by OrganicIrradiation** [comment]
Good point. Could also use some more test cases that don't ping GS more. Feel free to modify test.py and send a PR.

**Comment by ipeirotis** [comment]
Implemented.
