### ISSUE TITLE
[Question] scholarly to retrieve the year of publication of all citing works

### ISSUE THREAD

**Issue by mheskett** [OrganicIrradiation/scholarly#43]
Given a pub med ID or paper title, can you use scholarly to find the year of publication of all works that cited the given publication?  thanks!

**Comment by bayesfactor** [comment]
Or can we retrieve the publication year in the returned scholarly.scholarly.Publication object ?

**Comment by rsgoncalves** [comment]
It would be super helpful to be able to get the publication year of each Publication object.

**Comment by bayesfactor** [comment]
Please see my PR submitted 6 days ago that adds the functionality of returning year, as well as other information (journal, publisher)

**Comment by rsgoncalves** [comment]
@bayesfactor I've started using it and it works great, thanks a lot! Super useful to search based on a start/end year range (exactly what I was looking for).

**Comment by rsgoncalves** [comment]
@bayesfactor sometimes the venue/year strings only contain the year, and so after splitting by comma (in this [line](https://github.com/bayesfactor/scholarly/blob/a81b25c7ede9239b587c935c3fb8cd12107245cd/scholarly/scholarly.py#L163)) there is no 2nd item in the array. Also, sometimes there seems to be no stated publisher, somehow, and so the array item [here](https://github.com/bayesfactor/scholarly/blob/a81b25c7ede9239b587c935c3fb8cd12107245cd/scholarly/scholarly.py#L165) does not exist.

**Comment by ipeirotis** [comment]
This is possible. However, note that many citations do not have the year properly filled in:

```
search_query = scholarly.search_pubs_query("Building query optimizers for information extraction: The SQoUT project")
p = next(search_query)
filled = p.fill()
citation_year = [c.bib['year'] for c in filled.get_citedby()]
print(citation_year)
```

returns

```
[' 2013', ' 2010', ' 2009', ' 2011', ' 2011', ' 2013', ' 2012', ' 2012', ' 2012', 'NA', ' 2019', ' 2010', 'NA', 'NA', ' 2018', 'NA', 'NA', 'NA', 'NA', ' 2015']
```
