### ISSUE TITLE
empty get_citedby()

### ISSUE THREAD

**Issue by ddfir** [OrganicIrradiation/scholarly#47]
The method pub.get_citedby() returns an empty set even for publications with more than zero citations. I suspect that the attribute id_scholarcitedby is not set by fill() as expected.

**Comment by cerkut** [comment]
Same here, there is no 'id_scholarcitedby' in the filled record. 
`# Take a closer look at the 19th publication
pub = author.publications[18].fill()
print(pub)

 :results:
{'_filled': True,
  'bib': {'eprint': 'http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.218.9002&rep=rep1&type=pdf',
	  'journal': 'Proceedings of the Digital Audio Effects Workshop '
		     '(DAFx’08)',
	  'title': 'Inferring the hand configuration from hand clapping sounds',
	  'url': 'http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.218.9002&rep=rep1&type=pdf',
	  'year': 2008},
  'citedby': 21,
  'id_citations': 'NPYFs5EAAAAJ:Se3iqnhoufwC',
  'source': 'citations'}
 :end:

# Which papers cited that publication?
print([citation.bib['title'] for citation in pub.get_citedby()])

:results:
output
[]
`

**Comment by pelednoam** [comment]
Same here.
When looking into the source code of the requested web page, I saw this error:
"Sorry, we can't verify that you're not a robot when JavaScript is turned off"
Looks like Google Scholar had enough...

**Comment by lubianat** [comment]
Same here...

**Comment by Davide57** [comment]
Same here.

**Comment by Davide57** [comment]
I solved the issue by editing scholarly.py. I edited the Publisher init method as follow:
`def __init__(self, __data, pubtype=None):
      
        self.bib = dict()
        self.source = pubtype
        if self.source == 'citations':
            self.bib['title'] = __data.find('a', class_='gsc_a_at').text
            self.id_citations = re.findall(_CITATIONPUBRE, __data.find('a', class_='gsc_a_at')['data-href'])[0]
            citedby = __data.find(class_='gsc_a_ac')
            if citedby and not (citedby.text.isspace() or citedby.text == ''):
                self.citedby = int(citedby.text)
            year = __data.find(class_='gsc_a_h')
            if year and year.text and not year.text.isspace() and len(year.text)>0:
                self.bib['year'] = int(year.text)

            ### NEW CODE ###
            href = __data.find('a',"gsc_a_ac")
            url = (((str(href).split(" "))[3]).split(">"))[0]
            
            citeslist = url.split("cites=")
            cites = []
            if len(citeslist) > 1: 
                cites = (citeslist[1][:-1]).split(",")
            
            self.id_scholarcitedby = cites
            ### END NEW CODE ###
        elif self.source == 'scholar':
            databox = __data.find('div', class_='gs_ri')
            title = databox.find('h3', class_='gs_rt')
            if title.find('span', class_='gs_ctu'): # A citation
                title.span.extract()
            elif title.find('span', class_='gs_ctc'): # A book or PDF
                title.span.extract()
            self.bib['title'] = title.text.strip()
            if title.find('a'):
                self.bib['url'] = title.find('a')['href']
            authorinfo = databox.find('div', class_='gs_a')
            self.bib['author'] = ' and '.join([i.strip() for i in authorinfo.text.split(' - ')[0].split(',')])
            if databox.find('div', class_='gs_rs'):
                self.bib['abstract'] = databox.find('div', class_='gs_rs').text
                if self.bib['abstract'][0:8].lower() == 'abstract':
                    self.bib['abstract'] = self.bib['abstract'][9:].strip()
            lowerlinks = databox.find('div', class_='gs_fl').find_all('a')
           
            for link in lowerlinks:
                if 'Import into BibTeX' in link.text:
                    self.url_scholarbib = link['href']
                if 'Cited by' in link.text:
                    self.citedby = int(re.findall(r'\d+', link.text)[0])
                    self.id_scholarcitedby = re.findall(_SCHOLARPUBRE, link['href'])[0]
            if __data.find('div', class_='gs_ggs gs_fl'):
                self.bib['eprint'] = __data.find('div', class_='gs_ggs gs_fl').a['href']
        self._filled = False`
In this method I extracted the list of cited publications from the url and pushed it into id_scholarcitedby. 

After that, I also had to edit the get_citedby method in the Author class:
```
def get_citedby(self):
        """Searches GScholar for other articles that cite this Publication and
        returns a Publication generator.
        """
        if not hasattr(self, 'id_scholarcitedby'):
            self.fill()
        if hasattr(self, 'id_scholarcitedby'):
            ### NEW CODE ###
            stringcites = ""
            for cite in self.id_scholarcitedby:
                stringcites += urllib.parse.quote(bytes(cite, encoding='utf8')) + ","
            
            url = _SCHOLARPUB.format(requests.utils.quote(stringcites))
            ### END NEW CODE ###
            soup = _get_soup(_HOST+url)
            return _search_scholar_soup(soup)
        else:
            return []
```

I had to transform the list of strings in a format that is acceptable from the requests lib. To do that, I had to import "urllib" library too.

**Comment by ddfir** [comment]
The fix works perfectly, thanks!

**Comment by liujiajun** [comment]
Also face the same issue. The PR seems outdated. Any input on this?

**Comment by ddfir** [comment]
Fix by davide-coccomini worked for me

**Comment by ipeirotis** [comment]
@liujiajun Could you please paste the code that generates the issue? Perhaps the latest version on `master` solves the issue?

**Comment by ipeirotis** [comment]
Latest version from git fixes the issue:

```bash
pip3 install -U git+https://github.com/OrganicIrradiation/scholarly.git
```

Then
```python
from scholarly import scholarly
search_query = scholarly.search_pubs_query("Inferring the hand configuration from hand clapping sounds")
p = next(search_query)
print(p)
```
returns
```
{'_filled': False,
 'bib': {'abstract': 'In this paper, a technique for inferring the '
                     "configuration of a clapper's hands from a hand clapping "
                     'sound is described. The method was developed based on '
                     'analysis of synthetic and recorded hand clap sounds, '
                     'labeled with the corresponding hand configurations. A '
                     'naïve Bayes classifier was constructed to automatically '
                     'classify the data using two different feature sets. The '
                     'results indicate that the approach is applicable for '
                     'inferring the hand configuration.',
         'author': 'A Jylhä and C Erkut',
         'eprint': 'http://www.academia.edu/download/51406561/dafx08_52.pdf',
         'title': 'Inferring the hand configuration from hand clapping sounds',
         'url': 'http://www.academia.edu/download/51406561/dafx08_52.pdf',
         'venue': 'Proceedings of the Digital Audio Effects Workshop …',
         'year': ' 2008'},
 'citedby': 25,
 'id_scholarcitedby': '11635013584138118110',
 'nav': <scholarly._navigator.Navigator object at 0x7f91a1255630>,
 'source': 'scholar',
 'url_scholarbib': 'https://scholar.googleusercontent.com/scholar.bib?q=info:3qNltzXfd6EJ:scholar.google.com/&output=citation&scisdr=CgU4ogifGAA:AAGBfm0AAAAAXsKvl9ELIHj4D0jHtLttCA0piKvHJ6Aw&scisig=AAGBfm0AAAAAXsKvlyjTsCCDCiaEwfvcQSij77jd05SL&scisf=4&ct=citation&cd=0&hl=en'}
```

Then

```python
filled = p.fill()
print(filled)
```

gives

```
{'_filled': True,
 'bib': {'ENTRYTYPE': 'inproceedings',
         'ID': 'jylha2008inferring',
         'abstract': 'In this paper, a technique for inferring the '
                     "configuration of a clapper's hands from a hand clapping "
                     'sound is described. The method was developed based on '
                     'analysis of synthetic and recorded hand clap sounds, '
                     'labeled with the corresponding hand configurations. A '
                     'naïve Bayes classifier was constructed to automatically '
                     'classify the data using two different feature sets. The '
                     'results indicate that the approach is applicable for '
                     'inferring the hand configuration.',
         'author': 'Jylh{\\"a}, Antti and Erkut, Cumhur',
         'booktitle': 'Proceedings of the Digital Audio Effects Workshop '
                      '(DAFx’08)',
         'eprint': 'http://www.academia.edu/download/51406561/dafx08_52.pdf',
         'pages': '301--304',
         'title': 'Inferring the hand configuration from hand clapping sounds',
         'url': 'http://www.academia.edu/download/51406561/dafx08_52.pdf',
         'venue': 'Proceedings of the Digital Audio Effects Workshop …',
         'year': '2008'},
 'citedby': 25,
 'id_scholarcitedby': '11635013584138118110',
 'nav': <scholarly._navigator.Navigator object at 0x7f91a1255630>,
 'source': 'scholar',
 'url_scholarbib': 'https://scholar.googleusercontent.com/scholar.bib?q=info:3qNltzXfd6EJ:scholar.google.com/&output=citation&scisdr=CgU4ogifGAA:AAGBfm0AAAAAXsKvl9ELIHj4D0jHtLttCA0piKvHJ6Aw&scisig=AAGBfm0AAAAAXsKvlyjTsCCDCiaEwfvcQSij77jd05SL&scisf=4&ct=citation&cd=0&hl=en'}
```

and finally

```
>>> citations = [c for c in filled.get_citedby()]
>>> print(len(citations))

25
```



```
