### ISSUE TITLE
scholarly has no attribute use_proxy() 

### ISSUE THREAD

**Issue by karthiktadepalli1** [OrganicIrradiation/scholarly#51]
I initially installed the PyPI distribution, then realized that `use_proxy()` wasn't included in the PyPI distribution but only in the GitHub repo. So I uninstalled the PyPI distribution with 

`pip uninstall scholarly` 

and reinstalled from GitHub with 

`pip install git+https://github.com/OrganicIrradiation/scholarly.git` 

I've looked at the `scholarly.py` file in my library now and confirmed that it includes the `use_proxy()` function. 

However, when I try to call `scholarly.use_proxy()`, I get the following error:

`AttributeError: module 'scholarly' has no attribute 'use_proxy'`

I'm not sure what could be causing this. Any suggestions?

**Comment by nembrinj** [comment]
I had the same problem and could make it to work by adding

    from .scholarly import use_proxy

in the __init__.py file

**Comment by karthiktadepalli1** [comment]
Which `__init__.py` file? If I try this import statement in the code that actually calls scholarly, then it gives the error 

`ModuleNotFoundError: No module named '__main__.scholarly'; '__main__' is not a package`

**Comment by karthiktadepalli1** [comment]
That fixed it! I didn't know what `__init__.py` file you were referring to, but I added that line to the `__init__.py` file in my local scholarly library, and it worked.
