### ISSUE TITLE
When year is in format "YYYY/M" throws error

### ISSUE THREAD

**Issue by silvavn** [OrganicIrradiation/scholarly#55]
arrow.parser.ParserError: Could not match input '2011/5' to any of the following formats: YYYY-MM-DD, YYYY-M-DD, YYYY-M-D, YYYY/MM/DD, YYYY/M/DD, YYYY/M/D, YYYY.MM.DD, YYYY.M.DD, YYYY.M.D, YYYYMMDD, YYYY-DDDD, YYYYDDDD, YYYY-MM, YYYY/MM, YYYY.MM, YYYY

**Comment by ipeirotis** [comment]
Merging request with https://github.com/OrganicIrradiation/scholarly/issues/63
