### ISSUE TITLE
bibtex information, Publication fill,and url_scholarbib

### ISSUE THREAD

**Issue by leokaplan** [OrganicIrradiation/scholarly#57]
Hi, 
I am always receiving AttributeError: 'Publication' object has no attribute 'url_scholarbib' when trying to do pub.fill()

I believe that the error lies in https://github.com/OrganicIrradiation/scholarly/blob/867f740f61d05c10925e502b56d4bcdf1b1849cb/scholarly/scholarly.py#L168

Scholar changed their simple link to a modal created via js. (class `gs_or_cit gs_nph`)
I don't really know how would you like to implement this kind of click, but would be glad to help.

**Comment by mariosScope** [comment]
Hi, @leokaplan, I have the same problem but the reason is my location. Google scholar replys in spanish. Instead of  'Import into BibTeX'  I get 'Importar al BibTeX' 
> I am always receiving AttributeError: 'Publication' object has no attribute 'url_scholarbib' when trying to do pub.fill()

So it doesn´t find that specific text as a result I don´t get the url_scholarbib attribute.

**Comment by ffont** [comment]
While package is not updated, you can monkeypatch URLs to force scholar return results in english. Eg:

```
scholarly.scholarly._PUBSEARCH = "/scholar?hl=en&q={0}"
```

**Comment by ozars** [comment]
Thanks @ffont. This workaround solved the issue for me.
