### ISSUE TITLE
AttributeError when publication was not yet cited 

### ISSUE THREAD

**Issue by theMAC9** [OrganicIrradiation/scholarly#61]
When trying to use pub.citedby on a publication that has not yet been cited, scholarly throws an AttributeError.

I believe that initializing "citedby" per default with 0 during __init__ would be beneficial.

-->

        self.bib = dict()
        self.source = pubtype
        """Init citedby with 0 to avoid AttributeError"""
        self.citedby = int(0)

**Comment by ipeirotis** [comment]
Confirming the bug. Minimal code to replicate:

```python
search_query = scholarly.search_pubs_query("Demand-Aware Career Path Recommendations: A Reinforcement Learning Approach")
p = next(search_query)
filled = p.fill()
print(filled.citedby)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-f7831d7fdac9> in <module>
----> 1 filled.citedby

AttributeError: 'Publication' object has no attribute 'citedby'
```

**Comment by silvavn** [comment]
I have addressed this bug [here](https://github.com/silvavn/scholarly/blob/master/scholarly/Publication.py) (line 81)

**Comment by ipeirotis** [comment]
The bug is there at v.0.3 as well.
