### ISSUE TITLE
Error: 403 Forbidden Error

### ISSUE THREAD

**Issue by koalaloveit** [OrganicIrradiation/scholarly#62]
Hello,

I am trying to use scholarly, but I got 403 error

The code I run is below 2 lines:
search_query = scholarly.search_author('Marty Banks, Berkeley')
print(next(search_query))

The error I got is: 

----> 1 search_query = scholarly.search_author('Marty Banks, Berkeley')
      2 print(next(search_query))

~/.local/lib/python3.6/site-packages/scholarly/scholarly.py in search_author(name)
    309     """Search by author name and return a generator of Author objects"""
    310     url = _AUTHSEARCH.format(requests.utils.quote(name))
--> 311     soup = _get_soup(_HOST+url)
    312     return _search_citation_soup(soup)
    313 

~/.local/lib/python3.6/site-packages/scholarly/scholarly.py in _get_soup(pagerequest)
     87 def _get_soup(pagerequest):
     88     """Return the BeautifulSoup for a page on scholar.google.com"""
---> 89     html = _get_page(pagerequest)
     90     html = html.replace(u'\xa0', u' ')
     91     return BeautifulSoup(html, 'html.parser')

~/.local/lib/python3.6/site-packages/scholarly/scholarly.py in _get_page(pagerequest)
     82         # return _get_page(re.findall(r'https:\/\/(?:.*?)(\/.*)', resp)[0])
     83     else:
---> 84         raise Exception('Error: {0} {1}'.format(resp.status_code, resp.reason))
     85 
     86 

Exception: Error: 403 Forbidden

I've been searching online on this for hours. Could someone kindly point me to the right direction?

Thank you a lot in advance!

Koala

**Comment by olaybobby** [comment]
Hi @koalaloveit 
I'm also having the same problem and looking for a solution....
Do you have any progress after that?

**Comment by koalaloveit** [comment]
Hi @olaybobby Unfortunately I haven't.... It seems like to be some permission issue. What progress have you made by the way?

**Comment by ipeirotis** [comment]
Please clone the latest version from Github and the packages for using proxies:

```
pip3 install -U git+https://github.com/OrganicIrradiation/scholarly.git
pip3 install -U free-proxy PySocks
```

and then use proxies or Tor:

## Proxies:
```
from fp.fp import FreeProxy
from scholarly import scholarly

proxy = FreeProxy(rand=True, timeout=1, country_id=['US', 'CA']).get()  
scholarly.use_proxy(http=proxy, https=proxy)

author = next(scholarly.search_author('Steven A Cholewiak'))
print(author)
````

## Tor

First, install Tor:

```
sudo apt-get install -y tor
```

and then


```
from scholarly import scholarly
# default values are shown below
proxies = {'http' : 'socks5://127.0.0.1:9050', 'https': 'socks5://127.0.0.1:9050'}
scholarly.use_proxy(**proxies)
# If proxy is correctly set up, the following runs through it
author = next(scholarly.search_author('Steven A Cholewiak'))
print(author)
```
