### ISSUE TITLE
scholarly.search_pubs_query() not working

### ISSUE THREAD

**Issue by aced125** [OrganicIrradiation/scholarly#65]
When I do 

```print(next(scholarly.search_pubs_query('Perception of physical stability and center of mass of 3D objects')))```

in an iPython kernel, I get a `StopIteration` error.

**Comment by aced125** [comment]
Upon some debugging, I have found that Google Scholar is asking me to login (probably because I sent too many requests).

Note, I also modified the source code locally to reduce the time between requests, so might be a reason for this.

**Comment by npeirson** [comment]
I get this also, with no modification to code. Cycling proxies might be a good idea, like [twitterscraper](https://github.com/taspinar/twitterscraper).

**Comment by ipeirotis** [comment]
Latest version from master should fix that. 

Also instead of 
```python
next(scholarly.search_pubs_query('Perception of physical stability and center of mass of 3D objects'))
```

try

```python
results = scholarly.search_pubs_query('Perception of physical stability and center of mass of 3D objects')
pubs = [p for p in results]
```
