### ISSUE TITLE
pub.fill() fails to parse because it does not enforce hl=en

### ISSUE THREAD

**Issue by ceriottm** [OrganicIrradiation/scholarly#67]
I noticed that pub.fill() couldn't retrieve all the fields. I realized it was fetching a localized version of the page, which was in German. Could fix the problem adding a hl=en option to all the search strings (lines 25-31 in scholarly.py) that didn't have it.

**Comment by ipeirotis** [comment]
Fixed through https://github.com/OrganicIrradiation/scholarly/pull/52
