### ISSUE TITLE
Get one paper bibliography

### ISSUE THREAD

**Issue by mbahin** [OrganicIrradiation/scholarly#68]
Hi,

Thanks for the nice tool! :)

I was wondering whether it's possible to retrieve all the papers cited (bibliography) in one paper.

Cheers,
Mathieu

**Comment by silvavn** [comment]
This library only retrieves papers and papers that cite it on Scholar. There is no feature that retrieves bibliography as of rn.

**Comment by mbahin** [comment]
Hi,

Thanks for your answer.
So I guess this is not something you're planning to develop?
Do you think it's "easy" to do? Are they some constraints making it impossible?

Cheers,
Mathieu

**Comment by silvavn** [comment]
i am not the main developer of this package, but I would say that is not
something that should be part of it. This package scrapes google scholar,
and that information is not present there.

There are other tools that scrape bibliography from papers. Its not
impossible but again its not on Scholar.

Victor Silva

This message was typed and sent from a mobile phone. Please excuse any
typos.
