### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by programehr** [OrganicIrradiation/scholarly#69]
Is there any rate limit? Is it possible to hit a cptcha or other limitation?

**Comment by silvavn** [comment]
There is an implicit rate limit provided by Google. We do hit captchas yes.

**Comment by JheeKeyth** [comment]
Is your scholarly.search pubs query () working? Mine is giving stop interaction, even using proxy and VPN.
What's strange is that the search for the author's name works perfectly.

**Comment by silvavn** [comment]
Yes, however I have developed my own branch of scholarly to circumvent such limitations

**Comment by ipeirotis** [comment]
Try the latest version from master using Tor. Not 100% failproof, but should get the work done for a good number of cases.
