### ISSUE TITLE
Scholarly stopped working.

### ISSUE THREAD

**Issue by jcd000** [OrganicIrradiation/scholarly#7]
The error happens when trying to fill author information:

`Traceback (most recent call last):
`
`File "test_scholarly.py", line 4, in <module>
`
`    author = next(scholarly.search_author('Einstein')).fill()
`
`File "scholarly.py", line 111, in _search_citation_soup
`
`    yield Author(row)
`
`File "scholarly.py", line 227, in __init__
`
`    self.name = __data.find('h3', class_='gsc_1usr_name').text
`
`AttributeError: 'NoneType' object has no attribute 'text'
`

I'm not familiar enough with beautifulsoup to track the problem, but my best guess is a change of the Google Scholar html format.

**Comment by OrganicIrradiation** [comment]
The page format has changed, so the scraping ids need to be updated.

**Comment by OrganicIrradiation** [comment]
@jcd000, could you confirm that the latest version https://github.com/OrganicIrradiation/scholarly/commit/11181618e053d1f9ca82a015b151ac5c0422c4bb works?

**Comment by jcd000** [comment]
Yes, it works well now.
Thank you very much, this is a useful module!
