### ISSUE TITLE
module 'scholarly' has no attribute 'use_proxy'

### ISSUE THREAD

**Issue by MarcosFP97** [OrganicIrradiation/scholarly#81]
First of all, thank you for your amazing work! I am interested in running scholarly through a proxy but when I install it I always obtain the same error: module 'scholarly' has no attribute 'use_proxy'. I have tried everything: installing through pip, cloning the repository, etc. I would appreciate any help.

**Comment by ipeirotis** [comment]
```
pip3 install -U git+https://github.com/OrganicIrradiation/scholarly.git
pip3 install -U free-proxy PySocks 
```

and then

```
from fp.fp import FreeProxy
from scholarly import scholarly

proxy = FreeProxy(rand=True, timeout=1, country_id=['US', 'CA']).get()  
scholarly.use_proxy(http=proxy, https=proxy)

author = next(scholarly.search_author('Steven A Cholewiak'))

print(author)
```

**Comment by MarcosFP97** [comment]
That worked! Thanks
