### ISSUE TITLE
after activating proxy always 'stop iteration'

### ISSUE THREAD

**Issue by MarcosFP97** [OrganicIrradiation/scholarly#86]
Hi! As I posted in a previous issue, I am trying to obtain Google Scholar content through a proxy using your function 'use_proxy'. However, once I activate it, the other functionalities such as 'search_author', always return an empty iterator and this didn't happen before using the proxy with the same queries ... 
I would appreciate any help.
Kind regards

**Comment by ipeirotis** [comment]
If free proxies do not work, try using Tor instead:

```
sudo apt-get install -y tor
pip3 install -U PySocks 
```

```
from scholarly import scholarly
# default values are shown below
proxies = {'http' : 'socks5://127.0.0.1:9050', 'https': 'socks5://127.0.0.1:9050'}
scholarly.use_proxy(**proxies)
# If proxy is correctly set up, the following runs through it
author = next(scholarly.search_author('Steven A Cholewiak'))
print(author)
```

**Comment by MarcosFP97** [comment]
Yes, free proxies didn't work, but I am able to use Tor as a proxy. Thank you.
Kinds regards
